name: Express js Version
on: [push, pull_request]
jobs:
  check-express-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: node -v