name: Check_Json_Web_Token_Version
on: [push]
jobs:
  check-jwt:
	  runs-on: ubuntu-latest
		steps:
			- uses: action/checkout@v2
			- uses: action/setup-node@v1
			- run: npm install --save jsonwebtoken
			- run: jsonwebtoken --version